src/objects/Territory_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Territory_Country__c</fullName>
        <label>Territory Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_State__c</fullName>
        <label>Territory State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Territory Assignment</label>
    <nameField>
        <displayFormat>TA-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Territory Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CTM_TerritoryRegionFieldHelper.cls
public class CTM_TerritoryRegionFieldHelper {
	private CTM_TerritoryRegionFieldHelper() {
	}
	
	private static CTM_TerritoryRegionFieldHelper INSTANCE;
	
	public static CTM_TerritoryRegionFieldHelper getInstance() {
		if (INSTANCE == null) {
			INSTANCE = new CTM_TerritoryRegionFieldHelper();
		}
		return INSTANCE;
	}
	 
	
	public SObjectField getTerritoryAssignmentRegionField(CTM_RegionTypeEnum regionType) {
		return (CTM_RegionTypeEnum.COUNTRY.equals(regionType)) 
				? Territory_Assignment__c.Territory_Country__c 
				: Territory_Assignment__c.Territory_State__c;
	}

	public SObjectField getAccountRegionField(CTM_RegionTypeEnum regionType) {
		return (CTM_RegionTypeEnum.COUNTRY.equals(regionType)) 
				? Account.BillingCountry 
				: Account.BillingState;
	}
    
}