src/objects/Territory_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Territory_Country__c</fullName>
        <label>Territory Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_State__c</fullName>
        <label>Territory State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Territory Assignment</label>
    <nameField>
        <displayFormat>TA-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Territory Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CTM_RegionTypeEnumHelper.cls
public class CTM_RegionTypeEnumHelper {
	private CTM_RegionTypeEnumHelper() {
	}

	private static CTM_RegionTypeEnumHelper INSTANCE; 
	
	public static CTM_RegionTypeEnumHelper getInstance() {
		if (INSTANCE == null) {
			INSTANCE = new CTM_RegionTypeEnumHelper();
		}
		return INSTANCE;
	}
	
   	public static final Boolean HAS_COUNTRY = true;
   	public static final Boolean NO_COUNTRY = false;
   	
	public CTM_RegionTypeEnum toEnum(Account account) {
		if (String.isBlank(account.BillingState)) {
			return null;
		}
		return this.toEnum(!String.isBlank(account.BillingCountry));
	}

	public CTM_RegionTypeEnum toEnum(Territory_Assignment__c territoryAssignment) {
		if (String.isBlank(territoryAssignment.Territory_State__c)) {
			return null;
		}
		return this.toEnum(!String.isBlank(territoryAssignment.Territory_Country__c));
	}
   	
   	public CTM_RegionTypeEnum toEnum(Boolean value) {
   		return HAS_COUNTRY
   			? CTM_RegionTypeEnum.COUNTRY
   			: CTM_RegionTypeEnum.STATE;
   	}
}