src/objects/XAP_REST_Request__c.object
<CustomObject>
    <fields>
        <fullName>Integration_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Integration User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Async_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Email__c</fullName>
        <label>New Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Target_Email__c</fullName>
        <label>Target Email</label>
        <type>Email</type>
    </fields>
    <label>REST Request</label>
    <nameField>
        <displayFormat>RRQ-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>REST Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REST Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/XAP_REST_RequestSelector.cls
public virtual class XAP_REST_RequestSelector extends XAP_DAO_SOQL_SObjectSelectorAbs {
    private XAP_REST_RequestSelector() {
    }

    private static XAP_REST_RequestSelector instance;

    public static XAP_REST_RequestSelector getInstance() {
        if (instance == null) {
            instance = new XAP_REST_RequestSelector();
        }
        return instance;
    }

    public override SObjectType getSObjectType() {
        return XAP_REST_Request__c.SObjectType;
    }

    private List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{
                XAP_REST_Request__c.Integration_User__c,
                XAP_REST_Request__c.New_Email__c,
                XAP_REST_Request__c.Target_Email__c
        };
    }
}