src/objects/XAP_ASYNC_Request__c.object
<CustomObject>
    <fields>
        <fullName>Async_Job_Id__c</fullName>
        <description>This should be a Master-Detail relationship to Async Job, but that&apos;s not supported.</description>
        <label>Async Job Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XAP_REST_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>REST Request</label>
        <referenceTo>XAP_REST_Request__c</referenceTo>
        <relationshipLabel>Async Requests</relationshipLabel>
        <relationshipName>REST_Request_Async_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SObject_Id__c</fullName>
        <label>SObject Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Async Request</label>
    <nameField>
        <displayFormat>RRQAJ-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>REST Request Async Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/XAP_REST_Request__c.object
<CustomObject>
    <label>REST Request</label>
    <nameField>
        <displayFormat>RRQ-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>REST Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REST Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/XAP_ASYNC_RequestSelector.cls
public virtual class XAP_ASYNC_RequestSelector extends XAP_DAO_SOQL_SObjectSelectorAbs {
    private XAP_ASYNC_RequestSelector() {
    }

    private static XAP_ASYNC_RequestSelector INSTANCE;

    public static XAP_ASYNC_RequestSelector getInstance() {
        if (INSTANCE == null) {
            INSTANCE = new XAP_ASYNC_RequestSelector();
        }
        return INSTANCE;
    }

    public override SObjectType getSObjectType() {
        return XAP_ASYNC_Request__c.SObjectType;
    }

    private List<SObjectField> getSObjectFieldList() {
        return new List<SObjectField>{
                XAP_ASYNC_Request__c.Id,
                XAP_ASYNC_Request__c.Async_Job_Id__c,
                XAP_ASYNC_Request__c.Class_Name__c,
                XAP_ASYNC_Request__c.XAP_REST_Request__c,
                XAP_ASYNC_Request__c.SObject_Id__c
        };
    }

    public virtual List<XAP_ASYNC_Request__c> selectByAsyncJobId(Set<Id> asyncJobIdSet) {
        return (List<XAP_ASYNC_Request__c>) Database.query(
                this.newQueryFactory()
                        .setCondition(new XAP_DAO_SOQL_WHERE_InIdSetClause(
                                XAP_ASYNC_Request__c.Async_Job_Id__c,
                                asyncJobIdSet
                        ))
                        .toSOQL()
        );
    }
}