src/objects/XAP_REST_Request__c.object
<CustomObject>
    <fields>
        <fullName>Headers__c</fullName>
        <label>Headers</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Http_Method__c</fullName>
        <label>Http Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DELETE</fullName>
                </value>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>HEAD</fullName>
                </value>
                <value>
                    <fullName>PATCH</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Params__c</fullName>
        <label>Params</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Remote_IP_Address__c</fullName>
        <label>Remote IP Address</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Body__c</fullName>
        <label>Request Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_URI__c</fullName>
        <label>Request URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resource_Path__c</fullName>
        <label>Resource Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>REST Request</label>
    <nameField>
        <displayFormat>RRQ-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>REST Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REST Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/XAP_REST_ResponseWrapper.cls
public virtual class XAP_REST_ResponseWrapper {
	XAP_ENC_EncodingUtilWrapper encodingUtilWrapper;
	XAP_UTIL_JsonHelper jsonHelper;
	
	@TestVisible public Map<String, String> headers {get; private set;}
	@TestVisible public String httpMethod {get; private set;}
	@TestVisible public Map<String, String> params {get; private set;}
	@TestVisible public String remoteIpAddress {get; private set;}
	@TestVisible public Blob requestBody {get; private set;}
	@TestVisible public String requestURI {get; private set;}
	@TestVisible public String resourcePath {get; private set;}
	
	public XAP_REST_ResponseWrapper(XAP_ENC_EncodingUtilWrapper encodingUtilWrapper, XAP_UTIL_JsonHelper jsonHelper) {
		this.encodingUtilWrapper = encodingUtilWrapper;
		this.jsonHelper = jsonHelper;
		
		RestRequest request = RestContext.request; 
		if (request != null) {
			this.headers = request.headers;
			this.httpMethod = request.httpMethod;
			this.params = request.params;
			this.remoteIpAddress = request.remoteAddress;
			this.requestBody = request.requestBody;
			this.requestURI = request.requestURI;
			this.resourcePath = request.resourcePath;
		}
	}
	
	public XAP_REST_ResponseWrapper() {
		this(new XAP_ENC_EncodingUtilWrapper(), new XAP_UTIL_JsonHelper());
	}
	
	public XAP_REST_Request__c exportAsRecord() {
		XAP_REST_Request__c request =  new XAP_REST_Request__c(
			Headers__c = this.jsonHelper.serialize(this.headers),
			Http_Method__c = this.httpMethod,
			Params__c = this.jsonHelper.serialize(this.params),
			Remote_IP_Address__c = this.remoteIpAddress,
			Request_URI__c = this.requestURI,
			Resource_Path__c = this.resourcePath
		);
		if (this.requestBody != null) {
			request.Request_Body__c = this.encodingUtilWrapper.base64Encode(this.requestBody);
		}
		return request;
	}
}