src/objects/XAP_REST_Request__c.object
<CustomObject>
    <fields>
        <fullName>Integration_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Integration User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Async_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Email__c</fullName>
        <label>New Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Params__c</fullName>
        <label>Params</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Target_Email__c</fullName>
        <label>Target Email</label>
        <type>Email</type>
    </fields>
    <label>REST Request</label>
    <nameField>
        <displayFormat>RRQ-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>REST Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REST Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/XAP_REST_RequestRecordFactory.cls
public virtual class XAP_REST_RequestRecordFactory {
    XAP_DAO_DML_GenericDml genericDml;
    XAP_REST_ResponseWrapper restResponseWrapper;
    XAP_UTIL_SObjectFieldNonnullTranscriber sObjectFieldTranscriber;

    public XAP_REST_RequestRecordFactory(
            XAP_DAO_DML_GenericDml genericDml,
            XAP_REST_ResponseWrapper restResponseWrapper,
            XAP_UTIL_SObjectFieldNonnullTranscriber sObjectFieldTranscriber
    ) {
        this.genericDml = genericDml;
        this.restResponseWrapper = restResponseWrapper;
        this.sObjectFieldTranscriber = sObjectFieldTranscriber;
    }

    public XAP_REST_RequestRecordFactory() {
        this(
                XAP_DAO_DML_GenericDml.getInstance(),
                new XAP_REST_ResponseWrapper(),
                new XAP_UTIL_SObjectFieldNonnullTranscriber()
        );
    }

    private static final List<SObjectField> TRANSCRIBED_FIELD_LIST = new List<SObjectField>{
            XAP_REST_Request__c.Integration_User__c,
            XAP_REST_Request__c.Target_Email__c,
            XAP_REST_Request__c.New_Email__c,
            XAP_REST_Request__c.Params__c
    };

    public virtual XAP_REST_Request__c createAndInsertFor(XAP_REST_Request__c contextRequest) {
        XAP_REST_Request__c restRequest = this.restResponseWrapper.exportAsRecord();

        XAP_REST_Request__c finalizedRequest = (XAP_REST_Request__c) this.sObjectFieldTranscriber
                .blend(restRequest, contextRequest, TRANSCRIBED_FIELD_LIST)
                .updatedSObject;

        this.genericDml.doInsert(new List<XAP_REST_Request__c>{
                finalizedRequest
        });
        return finalizedRequest;
    }
}