src/objects/XAP_ASYNC_Request__c.object
<CustomObject>
    <fields>
        <fullName>Async_Job_Id__c</fullName>
        <description>This should be a Master-Detail relationship to Async Job, but that&apos;s not supported.</description>
        <label>Async Job Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XAP_REST_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>REST Request</label>
        <referenceTo>XAP_REST_Request__c</referenceTo>
        <relationshipLabel>Async Requests</relationshipLabel>
        <relationshipName>REST_Request_Async_Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SObject_Id__c</fullName>
        <label>SObject Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Async Request</label>
    <nameField>
        <displayFormat>RRQAJ-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>REST Request Async Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/XAP_REST_Request__c.object
<CustomObject>
    <label>REST Request</label>
    <nameField>
        <displayFormat>RRQ-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>REST Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REST Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/XAP_ASYNC_RequestFactory.cls
public virtual class XAP_ASYNC_RequestFactory {
	XAP_UTIL_ClassHelper classHelper;
	
	public XAP_ASYNC_RequestFactory(XAP_UTIL_ClassHelper classHelper) {
		this.classHelper = classHelper;
	}
	
	public XAP_ASYNC_RequestFactory() {
		this(new XAP_UTIL_ClassHelper());
	} 
	
    public List<XAP_ASYNC_Request__c> createFor(Queueable queueable, List<SObject> sObjectList, Id asyncJobId) {
		List<XAP_ASYNC_Request__c> requestJobList = new List<XAP_ASYNC_Request__c>();
    	
    	if (String.isBlank(asyncJobId)) {
    		System.debug(LoggingLevel.WARN, 'asyncJobId is missing.');
    	
    		// SFDC may not provide this value for tests, causing integration tests to fail.  :-(	
    		if (Test.isRunningTest()) {
    			return requestJobList;	
    		}
    		// We want errors outside of testing conditions!
    	}

		for (SObject sObj : sObjectList) {
			requestJobList.add(new XAP_ASYNC_Request__c(
					Class_Name__c = this.classHelper.getClassName(queueable),
					SObject_Id__c = sObj.Id,
					XAP_REST_Request__c	= this.getCurrentRequestId(sObj),
					Async_Job_Id__c = asyncJobId
			));
		}
    	return requestJobList;
    }
    
    @TestVisible
    private Id getCurrentRequestId(SObject sObj) {
    	Id requestId;
		try  {
			requestId = (Id) sObj.get('Current_XAP_REST_Request__c');
		}
		catch (System.SObjectException ex) {
		}    	
		return requestId;
    }
    
    
}