src/objects/XAP_ASYNC_Request__c.object
<CustomObject>
    <fields>
        <fullName>Async_Job_Id__c</fullName>
        <description>This should be a Master-Detail relationship to Async Job, but that&apos;s not supported.</description>
        <label>Async Job Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Async Request</label>
    <nameField>
        <displayFormat>RRQAJ-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>REST Request Async Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/XAP_ASYNC_Result__c.object
<CustomObject>
    <fields>
        <fullName>Async_Job_Id__c</fullName>
        <label>Async Job Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>XAP_ASYNC_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Async Request</label>
        <referenceTo>XAP_XAP_ASYNC_Request__c</referenceTo>
        <relationshipLabel>Async Results</relationshipLabel>
        <relationshipName>Async_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cause__c</fullName>
        <label>Cause</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DML_Errors__c</fullName>
        <label>DML Errors</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Type_Name__c</fullName>
        <label>Exception Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unexpected_Exception__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Unexpected Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unhandled_Exception__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Unhandled Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unsaved_Record__c</fullName>
        <label>Unsaved Record</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Async Result</label>
    <nameField>
        <displayFormat>AR-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Async Results Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Results</pluralLabel>
    <recordTypes>
        <fullName>Failure</fullName>
        <active>true</active>
        <label>Failure</label>
    </recordTypes>
    <recordTypes>
        <fullName>Success</fullName>
        <active>true</active>
        <label>Success</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/XAP_ASYNC_ResultFactory.cls
public virtual class XAP_ASYNC_ResultFactory {
    XAP_UTIL_JsonHelper jsonHelper;

    public XAP_ASYNC_ResultFactory(XAP_UTIL_JsonHelper jsonHelper) {
        this.jsonHelper = jsonHelper;
    }

    public XAP_ASYNC_ResultFactory() {
        this(new XAP_UTIL_JsonHelper());
    }

    private static final String FAILURE_RECORD_TYPE_NAME = 'Failure';
    private static final String SUCCESS_RECORD_TYPE_NAME = 'Success';

    private static final Map<String, Schema.RecordTypeInfo> ASYNC_RESULT_RECORD_TYPE_INFO_BY_DEVELOPER_NAME_MAP
            = XAP_ASYNC_Result__c.SObjectType.getDescribe()
                    .getRecordTypeInfosByDeveloperName();
    private static final Id FAILURE_RECORD_TYPE_ID = ASYNC_RESULT_RECORD_TYPE_INFO_BY_DEVELOPER_NAME_MAP
            .get(FAILURE_RECORD_TYPE_NAME)
            .getRecordTypeId();
    private static final Id SUCCESS_RECORD_TYPE_ID = ASYNC_RESULT_RECORD_TYPE_INFO_BY_DEVELOPER_NAME_MAP
            .get(SUCCESS_RECORD_TYPE_NAME)
            .getRecordTypeId();

    public virtual List<XAP_ASYNC_Result__c> buildAsyncResultListFor(
            List<SObject> sObjectList,
            XAP_DAO_DML_ResultListWrapperIntf resultListWrapper,
            Id asyncJobId,
            Map<Id, XAP_ASYNC_Request__c> asyncRequestByRestRequestIdMap
    ) {
        List<XAP_ASYNC_Result__c> asyncResultList = new List<XAP_ASYNC_Result__c>();

        List<XAP_DAO_DML_ResultWrapperIntf> resultWrapperList = resultListWrapper.getResultWrapperList();
        for (Integer i = 0; i < sObjectList.size(); i++) {
            asyncResultList.add(
                    this.buildAsyncResultFor(
                            sObjectList[i],
                            resultWrapperList[i],
                            asyncJobId,
                            asyncRequestByRestRequestIdMap
                    )
            );
        }
        return asyncResultList;
    }

    @TestVisible
    private XAP_ASYNC_Result__c buildAsyncResultFor(
            SObject sObj,
            XAP_DAO_DML_ResultWrapperIntf resultWrapper,
            Id asyncJobId,
            Map<Id, XAP_ASYNC_Request__c> asyncRequestByRestRequestIdMap
    ) {
        Id restRequestId = this.getCurrentRequestId(sObj);
        Id asyncRequestId = (asyncRequestByRestRequestIdMap != null)
                ? asyncRequestByRestRequestIdMap.get(restRequestId).Id
                : null;

        return resultWrapper.isSuccess()
                ? createForSuccess(asyncJobId, asyncRequestId, restRequestId)
                : createForDmlFailure(asyncJobId, asyncRequestId, restRequestId, sObj, resultWrapper);
    }

    @TestVisible
    private Id getCurrentRequestId(SObject sObj) {
        Id requestId;
        try {
            requestId = (Id) sObj.get('Current_XAP_REST_Request__c');
        } catch (System.SObjectException ex) {
        }
        return requestId;
    }

    // Concrete XAP_ASYNC_Result__c records -------------------------------------------------

    public XAP_ASYNC_Result__c createForSuccess(Id asyncJobId, Id asyncRequestId, Id restRequestId) {
        return new XAP_ASYNC_Result__c(
                RecordTypeId = SUCCESS_RECORD_TYPE_ID,
                Async_Job_Id__c = asyncJobId,
                Async_Request__c = asyncRequestId,
                REST_Request__c = restRequestId
        );
    }

    public XAP_ASYNC_Result__c createForDmlFailure(
            Id asyncJobId,
            Id asyncRequestId,
            Id restRequestId,
            SObject unsavedSObject,
            XAP_DAO_DML_ResultWrapperIntf resultWrapper
    ) {
        return new XAP_ASYNC_Result__c(
                RecordTypeId = FAILURE_RECORD_TYPE_ID,
                Async_Job_Id__c = asyncJobId,
                Async_Request__c = asyncRequestId,
                REST_Request__c = restRequestId,

                Message__c = String.join(resultWrapper.getErrorList(), ';'),
                DML_Errors__c = this.jsonHelper.serialize(resultWrapper.getErrorList()),
                Unsaved_Record__c = this.jsonHelper.serialize(unsavedSObject),

                Unexpected_Exception__c = false,
                Unhandled_Exception__c = true
        );
    }

    public List<XAP_ASYNC_Result__c> createResultsForUnhandledExceptions(
            Id asyncJobId,
            Map<Id, XAP_ASYNC_Request__c> asyncRequestByRestRequestIdMap,
            Exception ex
    ) {
        List<XAP_ASYNC_Result__c> asyncResultList = new List<XAP_ASYNC_Result__c>();
        for (Id restRequestId : asyncRequestByRestRequestIdMap.keySet()) {

            Id asyncRequestId = (asyncRequestByRestRequestIdMap != null)
                    ? asyncRequestByRestRequestIdMap.get(restRequestId).Id
                    : null;

            asyncResultList.add(new XAP_ASYNC_Result__c(
                    RecordTypeId = FAILURE_RECORD_TYPE_ID,
                    Async_Job_Id__c = asyncJobId,
                    Async_Request__c = asyncRequestId,
                    REST_Request__c = restRequestId,

                    Exception_Type_Name__c = ex.getTypeName(),
                    Message__c = ex.getMessage(),
                    Cause__c = this.jsonHelper.serialize(ex.getCause()),
                    Line_Number__c = ex.getLineNumber(),
                    Stack_Trace__c = ex.getStackTraceString(),

                    Unexpected_Exception__c = true,
                    Unhandled_Exception__c = true
            ));
        }
        return asyncResultList;
    }
}